site_name: Press Start Game Jam
theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.expand
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - footnotes 
  - abbr
  - attr_list
  
nav:
  - index.md

plugins:
  - search:
      lang: it
  - mkdocs-video